// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LiStreamEF.Models
{
    public partial class PlaylistItem
    {
        public Guid SongId { get; set; }
        public Guid PlaylistId { get; set; }
        public Guid AddedBy { get; set; }
        public DateTime AddDate { get; set; }

        public virtual User AddedByNavigation { get; set; }
        public virtual Playlist Playlist { get; set; }
        public virtual Song Song { get; set; }
    }
}