// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LiStreamEF.Models
{
    public partial class Playlist
    {
        public Playlist()
        {
            PlaylistItems = new HashSet<PlaylistItem>();
        }

        public Guid PlaylistId { get; set; }
        public string Name { get; set; }
        public Guid Owner { get; set; }
        public DateTime CreationDate { get; set; }

        public virtual User OwnerNavigation { get; set; }
        public virtual ICollection<PlaylistItem> PlaylistItems { get; set; }
    }
}