// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LiStreamEF.Models
{
    public partial class Song
    {
        public Song()
        {
            PlaylistItems = new HashSet<PlaylistItem>();
            UserFavoriteSongs = new HashSet<UserFavoriteSong>();
            Artists = new HashSet<Artist>();
        }

        public Guid SongId { get; set; }
        public string Title { get; set; }
        public byte[] Data { get; set; }
        public Guid ArtistId { get; set; }
        public Guid? AlbumId { get; set; }
        public DateTime ReleaseDate { get; set; }
        public long PlayCount { get; set; }
        public int Lenght { get; set; }

        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual ICollection<PlaylistItem> PlaylistItems { get; set; }
        public virtual ICollection<UserFavoriteSong> UserFavoriteSongs { get; set; }

        public virtual ICollection<Artist> Artists { get; set; }
    }
}