// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LiStreamEF.Models
{
    public partial class UserFollowedPlayableCollection
    {
        public Guid FavoriteId { get; set; }
        public Guid UserId { get; set; }
        public Guid? PlaylistId { get; set; }
        public Guid? AlbumId { get; set; }

        public virtual Album Album { get; set; }
        public virtual Playlist Playlist { get; set; }
        public virtual User User { get; set; }
    }
}