// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LiStreamEF.Models
{
    public partial class User
    {
        public User()
        {
            PlaylistItems = new HashSet<PlaylistItem>();
            Playlists = new HashSet<Playlist>();
        }

        public Guid UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }

        public virtual ICollection<PlaylistItem> PlaylistItems { get; set; }
        public virtual ICollection<Playlist> Playlists { get; set; }
    }
}